version: '3.4'

services:
  threejsreact:
    image: threejsreact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
